# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtWidgets import QWidget, QDesktopWidget, QApplication
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QWidget):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 565)
        self.widget = QtWidgets.QWidget(Form)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)


        self.widget.setGeometry(QtCore.QRect(40, 40, 550, 500))
        self.widget.setStyleSheet("QPushButton{\n"
"    background-color :qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(51, 95, 255, 255), stop:1 rgba(153, 220, 255, 255));\n"
"    border : none;\n"
"    color :rgb(255, 255, 255);\n"
"    border-radius : 7px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(153, 220, 255, 255), stop:1 rgba(51, 95, 255, 184));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left : 5px;\n"
"    padding-top : 5px;\n"
"    background-color : rgb(52, 101, 164);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("border-image : url(:/images/wallhaven-8o5wvj_1000x1600.png);\n"
"border-top-left-radius : 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label_2.setStyleSheet("background-color :  rgba(0, 0, 0, 80);\n"
"border-top-left-radius : 50px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("wallhaven-8o5wvj_1000x1600.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 240, 430))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color : rgba(255, 255, 255,255);\n"
"border-bottom-right-radius : 50px;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(340, 80, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color : rbga(0, 0, 0, 200)")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(295, 150, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color : rgba(0, 0, 0, 0);\n"
"border : none;\n"
"border-bottom: 2px solid rgb(56, 169, 255);\n"
"color : rgba(0, 0, 0, 240);\n"
"padding-bottom : 7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(295, 215, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color : rgba(0, 0, 0, 0);\n"
"border : none;\n"
"border-bottom: 2px solid rgb(56,169, 255);\n"
"color : rgba(0, 0, 0, 240);\n"
"padding-bottom : 7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Loginkan = QtWidgets.QPushButton(self.widget)
        self.Loginkan.setGeometry(QtCore.QRect(295, 295, 190, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Loginkan.setFont(font)
        self.Loginkan.setAutoFillBackground(False)
        self.Loginkan.setStyleSheet("")
        self.Loginkan.setObjectName("Loginkan")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(300, 340, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color : rgb(85, 87, 83)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 231, 161))
        self.label_6.setStyleSheet("background-color :rgba(0, 36, 103, 120)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 70, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color : rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 143, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color :rgb(216, 230, 251)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color : rgb(233, 235, 251)")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.Loginkan.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=3))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Password"))
        self.Loginkan.setText(_translate("Form", "Log In"))
        self.label_5.setText(_translate("Form", "Forget username or password "))
        self.label_7.setText(_translate("Form", "Yukibara"))
        self.label_8.setText(_translate("Form", "Tugas besar Basis Data "))
        self.label_9.setText(_translate("Form", "A U T O"))

def center(ss):
        # geometry of the main window
        qr = ss.frameGeometry()

        # center point of screen
        cp = QDesktopWidget().availableGeometry().center()

        # move rectangle's center point to screen's center point
        qr.moveCenter(cp)

        # top left of rectangle becomes top left of window centering it
        ss.move(qr.topLeft())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    center(Form)
    Form.show()
    sys.exit(app.exec_())
